### ISSUE TITLE
Where is example 4??

### ISSUE THREAD

**Issue by HuntJason** [jannikbuschke/pragmatic-cqrs-with-asp-net-core-for-spas#1]
Trying to follow along with https://www.jannikbuschke.de/blog/cqrs-with-mediatr-and-odata/ and it states there is a "Sample 4" which doesn't exist in this repository.

What I am trying to accomlish is OData with CQRS in the way you have it set up plus having Swashbuckle generate a Swagger document.

**Comment by jannikbuschke** [comment]
Forgot to commit -__-
